declare @SrcMB as varchar(50); --Source Mark Book (copy from)
declare @DstMB as varchar(50); --Destination Mark Book (copy to)
declare @DstMBDesc as varchar(80); --Description of Destination Mark Book 
declare @NCYear as integer; --Year Group of Destination Mark Book 
declare @UpdateBy as varchar(50); 

set @SrcMB = 'Y7 Physical Education Faculty Markbook';
set @DstMB = 'Test Y8 Physical Education Faculty Markbook';
set @DstMBDesc = 'Test Copy Mark Book';
set @NCYear = 8;
set @UpdateBy = 'SuriyaTokachae10549307314624';

--1. Create Mark book  (in case destination mark book has not been created yet if already created we can skip this step)
insert into TblMarkBooksMarkBook (txtName,txtDescription,intCategory,blnGlobal,blnAutoLink,blnMin,blnMax,blnAvg,
blnMedian,blnTotalGrade,blnLock,blnAllowSubjectHeads,blnAllowDepartmentHeads,txtSubmitBy,txtLastEditedBy,dteSubmitDateTime)
select @DstMB,@DstMBDesc,intCategory,
blnGlobal,blnAutoLink,blnMin,blnMax,blnAvg,blnMedian,blnTotalGrade,blnLock,blnAllowSubjectHeads,blnAllowDepartmentHeads,
txtSubmitBy,txtLastEditedBy,dteSubmitDateTime
from TblMarkBooksMarkBook 
where txtName = @SrcMB; 

--2. Assign pupils to mark book : Insert into tblMarkBookAssignedPupils
insert into TblMarkBooksAssignedPupils (intMarkbook,txtSchoolID,txtSubmitBy,dteSubmitDateTime)
select a.TblMarkBooksMarkBookID,b.txtSchoolID,@UpdateBy,GETDATE()
from TblMarkBooksMarkBook a,TblPupilManagementPupils b 
where a.txtName like @SrcMB
and b.intSystemStatus = 1
and b.intNCYear = @NCYear;

--3. Link subjects to mark book : Insert into TblMarkBooksLink (Subject)
insert into TblMarkBooksLink (intMarkBook,intSubjectID,txtSubmitBy,dteSubmitDateTime)
select (select aa.TblMarkBooksMarkBookID from TblMarkBooksMarkBook aa 
		where aa.txtName = @DstMB),a.intSubjectID,@UpdateBy,GETDATE()
from TblMarkBooksLink a
inner join TblMarkBooksMarkBook b on b.TblMarkBooksMarkBookID = a.intMarkBook
where b.txtName = @SrcMB
and a.intSubjectID is not null; 

--4. Link sets to mark book : Insert into TblMarkBooksLink (Set)
insert into TblMarkBooksLink (intMarkBook,intSetID,txtSubmitBy,dteSubmitDateTime)
select b.TblMarkBooksMarkBookID,d.TblTeachingManagerSetsID,@UpdateBy,GETDATE()
from TblMarkBooksLink a
inner join TblMarkBooksMarkBook b on b.TblMarkBooksMarkBookID = a.intMarkBook
inner join TblTeachingManagerSubjects c on c.TblTeachingManagerSubjectsID = a.intSubjectID
inner join TblTeachingManagerSets d on d.intSubject = c.TblTeachingManagerSubjectsID
where b.txtName = @DstMB;

--5. Assign teachers to mark book : Insert to TblMarkBooksAssignedTeachers
insert into TblMarkBooksAssignedTeachers 
(intMarkbook,txtUserCode,blnAllowViewAllMarksOnGlobalMarkbook,txtSubmitBy,dteSubmitDateTime)
select b.TblMarkBooksMarkBookID,d.txtTeacher,0,@UpdateBy,GETDATE()
from TblMarkBooksLink a
inner join TblMarkBooksMarkBook b on b.TblMarkBooksMarkBookID = a.intMarkBook
inner join TblTeachingManagerSubjects c on c.TblTeachingManagerSubjectsID = a.intSubjectID
inner join TblTeachingManagerSubjectsTeachers d on d.intSubject = c.TblTeachingManagerSubjectsID
where b.txtName =@DstMB; 

--6. Copy tests from source mark book to destination mark book : Insert into TblMarkBooksTest
insert into TblMarkBooksTest (intAction,txtName,txtShortName,intGradeSet,intMarkBook,
blnLockBetweenDates,blnLock,blnDisplayTranspose,blnAutoGenerated,txtSubmitBy,dteSubmitDateTime)
select b.intAction, b.txtName,b.txtShortName,b.intGradeSet,
(select aa.TblMarkBooksMarkBookID from TblMarkBooksMarkBook aa where aa.txtName = @DstMB),
b.blnLockBetweenDates,b.blnLock,b.blnDisplayTranspose,b.blnAutoGenerated,@UpdateBy,GETDATE()
from TblMarkBooksMarkBook a
inner join TblMarkBooksTest b on b.intMarkBook = a.TblMarkBooksMarkBookID
where a.txtName = @SrcMB; 

--7. Create entries to mark book : Insert into TblMarkBooksEntry
insert into TblMarkBooksEntry (txtSchoolID,intTest,txtSubmitBy,dteSubmitDateTime)
select c.txtSchoolID,b.TblMarkBooksTestID,@UpdateBy,GETDATE()
from (TblMarkBooksMarkBook a 
inner join TblMarkBooksTest b on b.intMarkBook = a.TblMarkBooksMarkBookID),
(select * from TblPupilManagementPupils c where c.intSystemStatus = 1 and c.intNCYear = @NCYear) c
where a.txtName = @DstMB;

--8. Copy marks from source mark book to destination mark book 
--Take below results and run in another SQL query window
select 'insert into TblMarkBooksMark(intEntry,txtMark,txtSubmitBy,dteSubmitDateTime) values'
+'('+cast(c.TblMarkBooksEntryID as varchar(10))+','''+d.txtMark+''','''+@UpdateBy +''',GETDATE());'
from TblMarkBooksMarkBook a
inner join TblMarkBooksTest b on b.intMarkBook = a.TblMarkBooksMarkBookID
inner join TblMarkBooksEntry c on c.intTest = b.TblMarkBooksTestID
inner join (select b.txtName,b.txtShortName,c.txtSchoolID,d.txtMark
from TblMarkBooksMarkBook a
inner join TblMarkBooksTest b on b.intMarkBook = a.TblMarkBooksMarkBookID
inner join TblMarkBooksEntry c on c.intTest = b.TblMarkBooksTestID
inner join TblMarkBooksMark d on d.intEntry = c.TblMarkBooksEntryID
where a.txtName like @SrcMB) d on d.txtName = b.txtName and d.txtSchoolID = c.txtSchoolID
where a.txtName like @DstMB;
